packages:
  # 核心业务包
  - 'packages/*'
  # Pro 组件包
  - 'packages/pro-components/*'

  # 组件站点
  - 'packages/*/site'

  # 公共工具（外部独立仓库，通过 git submodule 管理）
  - 'packages/tdesign-common/js'
  - 'packages/tdesign-common/docs'
  - 'packages/tdesign-common/style'

shamefullyHoist: true
