// AG-UI 标准协议事件 Mock 数据
// 基于 AG-UI 协议规范：https://docs.ag-ui.com

// AG-UI 标准事件类型
const AGUI_EVENT_TYPES = {
  TEXT_MESSAGE_START: 'TEXT_MESSAGE_START',
  TEXT_MESSAGE_CONTENT: 'TEXT_MESSAGE_CONTENT',
  TEXT_MESSAGE_END: 'TEXT_MESSAGE_END',
  TEXT_MESSAGE_CHUNK: 'TEXT_MESSAGE_CHUNK',
  THINKING_TEXT_MESSAGE_START: 'THINKING_TEXT_MESSAGE_START',
  THINKING_TEXT_MESSAGE_CONTENT: 'THINKING_TEXT_MESSAGE_CONTENT',
  THINKING_TEXT_MESSAGE_END: 'THINKING_TEXT_MESSAGE_END',
  TOOL_CALL_START: 'TOOL_CALL_START',
  TOOL_CALL_ARGS: 'TOOL_CALL_ARGS',
  TOOL_CALL_END: 'TOOL_CALL_END',
  TOOL_CALL_CHUNK: 'TOOL_CALL_CHUNK',
  TOOL_CALL_RESULT: 'TOOL_CALL_RESULT',
  THINKING_START: 'THINKING_START',
  THINKING_END: 'THINKING_END',
  STATE_SNAPSHOT: 'STATE_SNAPSHOT',
  STATE_DELTA: 'STATE_DELTA',
  MESSAGES_SNAPSHOT: 'MESSAGES_SNAPSHOT',
  RAW: 'RAW',
  CUSTOM: 'CUSTOM',
  RUN_STARTED: 'RUN_STARTED',
  RUN_FINISHED: 'RUN_FINISHED',
  RUN_ERROR: 'RUN_ERROR',
  STEP_STARTED: 'STEP_STARTED',
  STEP_FINISHED: 'STEP_FINISHED',
};

// 生成唯一的 runId
const generateRunId = () => `run_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;

// 生成唯一的 messageId
const generateMessageId = () => `msg_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;

// 生成唯一的 toolCallId
const generateToolCallId = () => `tool_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;

// 简化的AG-UI事件流（用于快速测试）
const simpleAguiChunks = [];

// 北京5日游旅游规划事件流
const tourChunks = [
  // 1. 运行开始
  {
    type: AGUI_EVENT_TYPES.RUN_STARTED,
    prompt: '请为我规划一个北京5日游行程',
    messageId: generateMessageId(),
    threadId: 'thread_001',
    runId: generateRunId(),
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  // 2. 初始状态快照
  {
    type: AGUI_EVENT_TYPES.STATE_SNAPSHOT,
    snapshot: {
      itinerary: null,
      userPreferences: null,
      status: 'init',
    },
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },

  // ========== 步骤1：查询天气 ==========
  // 状态变更：进入查询天气
  {
    type: AGUI_EVENT_TYPES.STATE_DELTA,
    delta: [{ op: 'replace', path: '/status', value: 'weather_querying' }],
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.STEP_STARTED,
    stepName: '查询天气',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.THINKING_START,
    title: '分析天气需求',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  { type: AGUI_EVENT_TYPES.THINKING_TEXT_MESSAGE_START, runId: null, agentId: 'travel-planner', timestamp: Date.now() },
  {
    type: AGUI_EVENT_TYPES.THINKING_TEXT_MESSAGE_CONTENT,
    delta: '用户需要了解北京5日天气以便安排行程。',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.THINKING_TEXT_MESSAGE_CONTENT,
    delta: '准备调用天气查询工具获取最新天气信息。',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  { type: AGUI_EVENT_TYPES.THINKING_TEXT_MESSAGE_END, runId: null, agentId: 'travel-planner', timestamp: Date.now() },
  {
    type: AGUI_EVENT_TYPES.THINKING_END,
    title: '思考结束',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TOOL_CALL_START,
    toolCallId: generateToolCallId(),
    toolCallName: 'get_weather_forecast',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TOOL_CALL_ARGS,
    toolCallId: null,
    delta: '{"city": "北京", "days": 5}',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TOOL_CALL_END,
    toolCallId: null,
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TOOL_CALL_RESULT,
    toolCallId: null,
    toolCallName: 'get_weather_forecast',
    content: JSON.stringify([
      { day: 1, high: 28, low: 18, condition: '晴' },
      { day: 2, high: 26, low: 17, condition: '多云' },
      { day: 3, high: 24, low: 16, condition: '小雨' },
      { day: 4, high: 27, low: 19, condition: '晴' },
      { day: 5, high: 29, low: 20, condition: '晴' },
    ]),
    role: 'tool',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_START,
    messageId: generateMessageId(),
    role: 'assistant',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '北京未来5天天气如下：',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '第1天：晴，28~18℃；第2天：多云，26~17℃；第3天：小雨，24~16℃；第4天：晴，27~19℃；第5天：晴，29~20℃。',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_END,
    messageId: null,
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.STATE_DELTA,
    delta: [
      {
        op: 'add',
        path: '/itinerary/weather',
        value: [
          { day: 1, high: 28, low: 18, condition: '晴' },
          { day: 2, high: 26, low: 17, condition: '多云' },
          { day: 3, high: 24, low: 16, condition: '小雨' },
          { day: 4, high: 27, low: 19, condition: '晴' },
          { day: 5, high: 29, low: 20, condition: '晴' },
        ],
      },
    ],
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.STEP_FINISHED,
    stepName: '查询天气',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  // 查询天气结束

  // ========== 步骤2：行程规划 ==========
  // 状态变更：进入行程规划
  {
    type: AGUI_EVENT_TYPES.STATE_DELTA,
    delta: [{ op: 'replace', path: '/status', value: 'planning' }],
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.STEP_STARTED,
    stepName: '行程规划',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.THINKING_START,
    title: '分析行程需求',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  { type: AGUI_EVENT_TYPES.THINKING_TEXT_MESSAGE_START, runId: null, agentId: 'travel-planner', timestamp: Date.now() },
  {
    type: AGUI_EVENT_TYPES.THINKING_TEXT_MESSAGE_CONTENT,
    delta: '根据天气和用户兴趣，规划每日路线。',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.THINKING_TEXT_MESSAGE_CONTENT,
    delta: '优先安排晴天户外活动，雨天安排室内景点。',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  { type: AGUI_EVENT_TYPES.THINKING_TEXT_MESSAGE_END, runId: null, agentId: 'travel-planner', timestamp: Date.now() },
  {
    type: AGUI_EVENT_TYPES.THINKING_END,
    title: '思考结束',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TOOL_CALL_START,
    toolCallId: generateToolCallId(),
    toolCallName: 'plan_itinerary',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TOOL_CALL_ARGS,
    toolCallId: null,
    delta: '{"city": "北京", "days": 5, "weather": "晴/多云/小雨"}',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TOOL_CALL_END,
    toolCallId: null,
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TOOL_CALL_RESULT,
    toolCallId: null,
    toolCallName: 'plan_itinerary',
    content: JSON.stringify([
      { day: 1, activities: ['抵达北京', '入住酒店', '王府井步行街'] },
      { day: 2, activities: ['故宫博物院', '天安门广场', '北京烤鸭'] },
      { day: 3, activities: ['长城（八达岭）', '明十三陵', '京剧表演'] },
      { day: 4, activities: ['颐和园', '圆明园', '三里屯'] },
      { day: 5, activities: ['鸟巢', '水立方', '798艺术区', '返程'] },
    ]),
    role: 'tool',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_START,
    messageId: generateMessageId(),
    role: 'assistant',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '以下是为您定制的北京5日游行程：',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '第1天：抵达北京，入住酒店，王府井步行街。',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '第2天：故宫博物院，天安门广场，北京烤鸭。',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '第3天：长城（八达岭），明十三陵，京剧表演。',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '第4天：颐和园，圆明园，三里屯。',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '第5天：鸟巢，水立方，798艺术区，返程。',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_END,
    messageId: null,
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.STATE_DELTA,
    delta: [
      {
        op: 'add',
        path: '/itinerary/plan',
        value: [
          { day: 1, activities: ['抵达北京', '入住酒店', '王府井步行街'] },
          { day: 2, activities: ['故宫博物院', '天安门广场', '北京烤鸭'] },
          { day: 3, activities: ['长城（八达岭）', '明十三陵', '京剧表演'] },
          { day: 4, activities: ['颐和园', '圆明园', '三里屯'] },
          { day: 5, activities: ['鸟巢', '水立方', '798艺术区', '返程'] },
        ],
      },
    ],
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.STEP_FINISHED,
    stepName: '行程规划',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  // 行程规划结束

  // ========== 步骤3：酒店推荐 ==========
  // 状态变更：进入酒店推荐
  {
    type: AGUI_EVENT_TYPES.STATE_DELTA,
    delta: [{ op: 'replace', path: '/status', value: 'hotel_recommending' }],
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.STEP_STARTED,
    stepName: '酒店推荐',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.THINKING_START,
    title: '分析酒店需求',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  { type: AGUI_EVENT_TYPES.THINKING_TEXT_MESSAGE_START, runId: null, agentId: 'travel-planner', timestamp: Date.now() },
  {
    type: AGUI_EVENT_TYPES.THINKING_TEXT_MESSAGE_CONTENT,
    delta: '根据行程和预算，筛选合适酒店。',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.THINKING_TEXT_MESSAGE_CONTENT,
    delta: '优先推荐交通便利、评分高的酒店。',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  { type: AGUI_EVENT_TYPES.THINKING_TEXT_MESSAGE_END, runId: null, agentId: 'travel-planner', timestamp: Date.now() },
  {
    type: AGUI_EVENT_TYPES.THINKING_END,
    title: '思考结束',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TOOL_CALL_START,
    toolCallId: generateToolCallId(),
    toolCallName: 'get_hotel_details',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TOOL_CALL_ARGS,
    toolCallId: null,
    delta: '{"location": "王府井", "budget": "中等"}',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TOOL_CALL_END,
    toolCallId: null,
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TOOL_CALL_RESULT,
    toolCallId: null,
    toolCallName: 'get_hotel_details',
    content: JSON.stringify([
      { name: '北京王府井希尔顿酒店', rating: 4.8, price: 1200 },
      { name: '北京长城脚下的公社', rating: 4.5, price: 800 },
      { name: '北京四合院宾馆', rating: 4.2, price: 600 },
    ]),
    role: 'tool',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_START,
    messageId: generateMessageId(),
    role: 'assistant',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '为您推荐以下酒店：',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '1. 北京王府井希尔顿酒店（4.8分，¥1200/晚）',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '2. 北京长城脚下的公社（4.5分，¥800/晚）',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '3. 北京四合院宾馆（4.2分，¥600/晚）',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_END,
    messageId: null,
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.STATE_DELTA,
    delta: [
      {
        op: 'add',
        path: '/itinerary/hotels',
        value: [
          { name: '北京王府井希尔顿酒店', rating: 4.8, price: 1200 },
          { name: '北京长城脚下的公社', rating: 4.5, price: 800 },
          { name: '北京四合院宾馆', rating: 4.2, price: 600 },
        ],
      },
    ],
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.STEP_FINISHED,
    stepName: '酒店推荐',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  // 酒店推荐结束

  // 终局快照和收尾
  // 状态变更：流程已完成
  {
    type: AGUI_EVENT_TYPES.STATE_DELTA,
    delta: [{ op: 'replace', path: '/status', value: 'finished' }],
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.MESSAGES_SNAPSHOT,
    messages: [
      { id: generateMessageId(), role: 'user', content: '请为我规划一个北京5日游行程' },
      { id: generateMessageId(), role: 'assistant', content: '为您推荐以下酒店：1. 北京王府井希尔顿酒店...' },
    ],
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.CUSTOM,
    event: { tip: '节假日景点可能拥堵，请提前规划。' },
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.RAW,
    event: { content: '行程规划完成', metadata: { source: 'travel-planner' } },
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.RUN_FINISHED,
    threadId: 'thread_001',
    runId: null,
    result: { totalAttractions: 8, estimatedCost: 5000, duration: '5天4晚' },
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
];
export { simpleAguiChunks, tourChunks, AGUI_EVENT_TYPES };
