// AG-UI 标准协议事件 Mock 数据
// 基于 AG-UI 协议规范：https://docs.ag-ui.com

// AG-UI 标准事件类型
const AGUI_EVENT_TYPES = {
  TEXT_MESSAGE_START: 'TEXT_MESSAGE_START',
  TEXT_MESSAGE_CONTENT: 'TEXT_MESSAGE_CONTENT',
  TEXT_MESSAGE_END: 'TEXT_MESSAGE_END',
  TEXT_MESSAGE_CHUNK: 'TEXT_MESSAGE_CHUNK',
  THINKING_TEXT_MESSAGE_START: 'THINKING_TEXT_MESSAGE_START',
  THINKING_TEXT_MESSAGE_CONTENT: 'THINKING_TEXT_MESSAGE_CONTENT',
  THINKING_TEXT_MESSAGE_END: 'THINKING_TEXT_MESSAGE_END',
  TOOL_CALL_START: 'TOOL_CALL_START',
  TOOL_CALL_ARGS: 'TOOL_CALL_ARGS',
  TOOL_CALL_END: 'TOOL_CALL_END',
  TOOL_CALL_CHUNK: 'TOOL_CALL_CHUNK',
  TOOL_CALL_RESULT: 'TOOL_CALL_RESULT',
  THINKING_START: 'THINKING_START',
  THINKING_END: 'THINKING_END',
  STATE_SNAPSHOT: 'STATE_SNAPSHOT',
  STATE_DELTA: 'STATE_DELTA',
  MESSAGES_SNAPSHOT: 'MESSAGES_SNAPSHOT',
  RAW: 'RAW',
  CUSTOM: 'CUSTOM',
  RUN_STARTED: 'RUN_STARTED',
  RUN_FINISHED: 'RUN_FINISHED',
  RUN_ERROR: 'RUN_ERROR',
  STEP_STARTED: 'STEP_STARTED',
  STEP_FINISHED: 'STEP_FINISHED',
};

// 生成唯一的 runId
const generateRunId = () => `run_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;

// 生成唯一的 messageId
const generateMessageId = () => `msg_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;

// 生成唯一的 toolCallId
const generateToolCallId = () => `tool_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;

// 简化的AG-UI事件流（用于快速测试）
const simpleAguiChunks = [];

// 北京5日游旅游规划事件流
const tourChunks = [
  // 1. 运行开始
  {
    type: AGUI_EVENT_TYPES.RUN_STARTED,
    prompt: '请为我规划一个北京5日游行程',
    messageId: generateMessageId(),
    threadId: 'thread_001',
    runId: generateRunId(),
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  // 2. 初始状态快照
  {
    type: AGUI_EVENT_TYPES.STATE_SNAPSHOT,
    snapshot: {
      itinerary: null,
      userPreferences: null,
      status: 'init',
    },
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },

  // ========== 步骤1：查询天气 ==========
  // 状态变更：进入查询天气
  {
    type: AGUI_EVENT_TYPES.STATE_DELTA,
    delta: [{ op: 'replace', path: '/status', value: 'weather_querying' }],
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.STEP_STARTED,
    stepName: '查询天气',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.THINKING_START,
    title: '分析天气需求',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  { type: AGUI_EVENT_TYPES.THINKING_TEXT_MESSAGE_START, runId: null, agentId: 'travel-planner', timestamp: Date.now() },
  {
    type: AGUI_EVENT_TYPES.THINKING_TEXT_MESSAGE_CONTENT,
    delta: '用户需要了解北京5日天气以便安排行程。',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.THINKING_TEXT_MESSAGE_CONTENT,
    delta: '准备调用天气查询工具获取最新天气信息。',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  { type: AGUI_EVENT_TYPES.THINKING_TEXT_MESSAGE_END, runId: null, agentId: 'travel-planner', timestamp: Date.now() },
  {
    type: AGUI_EVENT_TYPES.THINKING_END,
    title: '思考结束',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TOOL_CALL_START,
    toolCallId: generateToolCallId(),
    toolCallName: 'get_weather_forecast',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TOOL_CALL_ARGS,
    toolCallId: null,
    delta: '{"city": "北京", "days": 5}',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TOOL_CALL_END,
    toolCallId: null,
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TOOL_CALL_RESULT,
    toolCallId: null,
    toolCallName: 'get_weather_forecast',
    content: JSON.stringify([
      { day: 1, high: 28, low: 18, condition: '晴' },
      { day: 2, high: 26, low: 17, condition: '多云' },
      { day: 3, high: 24, low: 16, condition: '小雨' },
      { day: 4, high: 27, low: 19, condition: '晴' },
      { day: 5, high: 29, low: 20, condition: '晴' },
    ]),
    role: 'tool',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_START,
    messageId: generateMessageId(),
    role: 'assistant',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '## 🌤️ 北京未来5天天气预报\n\n',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '根据最新气象数据，为您整理了详细的天气信息：\n\n',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '| 日期 | 天气 | 温度 | 建议 |\n|------|------|------|------|\n',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '| **第1天** | ☀️ 晴 | 28°C ~ 18°C | 适合户外活动 |\n',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '| **第2天** | ⛅ 多云 | 26°C ~ 17°C | 天气舒适宜人 |\n',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '| **第3天** | 🌧️ 小雨 | 24°C ~ 16°C | 建议室内活动 |\n',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '| **第4天** | ☀️ 晴 | 27°C ~ 19°C | 适合游览景点 |\n',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '| **第5天** | ☀️ 晴 | 29°C ~ 20°C | 完美的旅行天气 |\n\n',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '> 💡 **温馨提示**：第3天有小雨，建议携带雨具，其他时间天气良好，适合户外游览。',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_END,
    messageId: null,
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.STATE_DELTA,
    delta: [
      {
        op: 'add',
        path: '/itinerary/weather',
        value: [
          { day: 1, high: 28, low: 18, condition: '晴' },
          { day: 2, high: 26, low: 17, condition: '多云' },
          { day: 3, high: 24, low: 16, condition: '小雨' },
          { day: 4, high: 27, low: 19, condition: '晴' },
          { day: 5, high: 29, low: 20, condition: '晴' },
        ],
      },
    ],
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.STEP_FINISHED,
    stepName: '查询天气',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  // 查询天气结束

  // ========== 步骤2：行程规划 ==========
  // 状态变更：进入行程规划
  {
    type: AGUI_EVENT_TYPES.STATE_DELTA,
    delta: [{ op: 'replace', path: '/status', value: 'planning' }],
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.STEP_STARTED,
    stepName: '行程规划',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.THINKING_START,
    title: '分析行程需求',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  { type: AGUI_EVENT_TYPES.THINKING_TEXT_MESSAGE_START, runId: null, agentId: 'travel-planner', timestamp: Date.now() },
  {
    type: AGUI_EVENT_TYPES.THINKING_TEXT_MESSAGE_CONTENT,
    delta: '根据天气和用户兴趣，规划每日路线。',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.THINKING_TEXT_MESSAGE_CONTENT,
    delta: '优先安排晴天户外活动，雨天安排室内景点。',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  { type: AGUI_EVENT_TYPES.THINKING_TEXT_MESSAGE_END, runId: null, agentId: 'travel-planner', timestamp: Date.now() },
  {
    type: AGUI_EVENT_TYPES.THINKING_END,
    title: '思考结束',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TOOL_CALL_START,
    toolCallId: generateToolCallId(),
    toolCallName: 'plan_itinerary',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TOOL_CALL_ARGS,
    toolCallId: null,
    delta: '{"city": "北京", "days": 5, "weather": "晴/多云/小雨"}',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TOOL_CALL_END,
    toolCallId: null,
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TOOL_CALL_RESULT,
    toolCallId: null,
    toolCallName: 'plan_itinerary',
    content: JSON.stringify([
      { day: 1, activities: ['抵达北京', '入住酒店', '王府井步行街'] },
      { day: 2, activities: ['故宫博物院', '天安门广场', '北京烤鸭'] },
      { day: 3, activities: ['长城（八达岭）', '明十三陵', '京剧表演'] },
      { day: 4, activities: ['颐和园', '圆明园', '三里屯'] },
      { day: 5, activities: ['鸟巢', '水立方', '798艺术区', '返程'] },
    ]),
    role: 'tool',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_START,
    messageId: generateMessageId(),
    role: 'assistant',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '## 📅 北京5日游精品行程\n\n',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '根据天气情况和景点特色，为您精心安排了以下行程：\n\n',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '### 🏮 第1天 - 初到北京\n',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '- **上午**：抵达北京，办理酒店入住\n- **下午**：🛍️ 王府井步行街购物体验\n- **晚上**：品尝地道北京小吃\n\n',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '### 🏛️ 第2天 - 皇城文化\n',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta:
      '- **上午**：🏯 **故宫博物院** - 探索紫禁城的辉煌历史\n- **下午**：🏛️ **天安门广场** - 感受首都的庄严气氛\n- **晚上**：🦆 **北京烤鸭** - 全聚德或便宜坊\n\n',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '### 🏔️ 第3天 - 长城之旅（雨天备选）\n',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta:
      '- **上午**：🏯 **八达岭长城** - 不到长城非好汉\n- **下午**：⚱️ **明十三陵** - 明朝皇陵群\n- **晚上**：🎭 **京剧表演** - 梅兰芳大剧院\n\n',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '### 🏞️ 第4天 - 皇家园林\n',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta:
      '- **上午**：🏞️ **颐和园** - 皇家园林的典范\n- **下午**：🌸 **圆明园** - 万园之园的遗址\n- **晚上**：🌃 **三里屯** - 体验北京夜生活\n\n',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '### 🏟️ 第5天 - 现代北京\n',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta:
      '- **上午**：🏟️ **鸟巢** - 国家体育场\n- **中午**：🏊 **水立方** - 国家游泳中心\n- **下午**：🎨 **798艺术区** - 当代艺术殿堂\n- **晚上**：✈️ 返程\n\n',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '> 🎯 **行程亮点**：涵盖古都文化、皇家园林、现代建筑，让您全方位体验北京的魅力！',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_END,
    messageId: null,
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.STATE_DELTA,
    delta: [
      {
        op: 'add',
        path: '/itinerary/plan',
        value: [
          { day: 1, activities: ['抵达北京', '入住酒店', '王府井步行街'] },
          { day: 2, activities: ['故宫博物院', '天安门广场', '北京烤鸭'] },
          { day: 3, activities: ['长城（八达岭）', '明十三陵', '京剧表演'] },
          { day: 4, activities: ['颐和园', '圆明园', '三里屯'] },
          { day: 5, activities: ['鸟巢', '水立方', '798艺术区', '返程'] },
        ],
      },
    ],
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.STEP_FINISHED,
    stepName: '行程规划',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  // 行程规划结束

  // ========== 步骤3：酒店推荐 ==========
  // 状态变更：进入酒店推荐
  {
    type: AGUI_EVENT_TYPES.STATE_DELTA,
    delta: [{ op: 'replace', path: '/status', value: 'hotel_recommending' }],
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.STEP_STARTED,
    stepName: '酒店推荐',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.THINKING_START,
    title: '分析酒店需求',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  { type: AGUI_EVENT_TYPES.THINKING_TEXT_MESSAGE_START, runId: null, agentId: 'travel-planner', timestamp: Date.now() },
  {
    type: AGUI_EVENT_TYPES.THINKING_TEXT_MESSAGE_CONTENT,
    delta: '根据行程和预算，筛选合适酒店。',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.THINKING_TEXT_MESSAGE_CONTENT,
    delta: '优先推荐交通便利、评分高的酒店。',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  { type: AGUI_EVENT_TYPES.THINKING_TEXT_MESSAGE_END, runId: null, agentId: 'travel-planner', timestamp: Date.now() },
  {
    type: AGUI_EVENT_TYPES.THINKING_END,
    title: '思考结束',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TOOL_CALL_START,
    toolCallId: generateToolCallId(),
    toolCallName: 'get_hotel_details',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TOOL_CALL_ARGS,
    toolCallId: null,
    delta: '{"location": "王府井", "budget": "中等"}',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TOOL_CALL_END,
    toolCallId: null,
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TOOL_CALL_RESULT,
    toolCallId: null,
    toolCallName: 'get_hotel_details',
    content: JSON.stringify([
      { name: '北京王府井希尔顿酒店', rating: 4.8, price: 1200 },
      { name: '北京长城脚下的公社', rating: 4.5, price: 800 },
      { name: '北京四合院宾馆', rating: 4.2, price: 600 },
    ]),
    role: 'tool',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_START,
    messageId: generateMessageId(),
    role: 'assistant',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '## 🏨 精选酒店推荐\n\n',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '根据您的行程安排和预算考虑，为您推荐以下优质酒店：\n\n',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '### 🌟 豪华型酒店\n',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta:
      '**🏨 北京王府井希尔顿酒店**\n- ⭐ 评分：**4.8分** (1,200+ 条评价)\n- 💰 价格：**¥1,200/晚**\n- 📍 位置：王府井商业街核心，步行可达故宫\n- ✨ 特色：国际五星标准，服务一流\n\n',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '### 🏞️ 特色型酒店\n',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta:
      '**🏔️ 北京长城脚下的公社**\n- ⭐ 评分：**4.5分** (800+ 条评价)\n- 💰 价格：**¥800/晚**\n- 📍 位置：八达岭长城附近，环境优美\n- ✨ 特色：建筑大师设计，独特艺术体验\n\n',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '### 🏮 经济型酒店\n',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta:
      '**🏠 北京四合院宾馆**\n- ⭐ 评分：**4.2分** (600+ 条评价)\n- 💰 价格：**¥600/晚**\n- 📍 位置：胡同区域，体验老北京风情\n- ✨ 特色：传统四合院建筑，性价比高\n\n',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta:
      '> 💡 **预订建议**：建议提前预订，旺季价格可能有所上涨。王府井希尔顿地理位置最佳，适合商务出行；长城脚下公社适合度假体验；四合院宾馆适合文化体验。',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_END,
    messageId: null,
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.STATE_DELTA,
    delta: [
      {
        op: 'add',
        path: '/itinerary/hotels',
        value: [
          { name: '北京王府井希尔顿酒店', rating: 4.8, price: 1200 },
          { name: '北京长城脚下的公社', rating: 4.5, price: 800 },
          { name: '北京四合院宾馆', rating: 4.2, price: 600 },
        ],
      },
    ],
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.STEP_FINISHED,
    stepName: '酒店推荐',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  // 酒店推荐结束

  // 终局快照和收尾
  // 状态变更：流程已完成
  {
    type: AGUI_EVENT_TYPES.STATE_DELTA,
    delta: [{ op: 'replace', path: '/status', value: 'finished' }],
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_START,
    messageId: generateMessageId(),
    role: 'assistant',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '## 📋 旅游规划总结\n\n',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '🎉 **恭喜！您的北京5日游行程规划已完成**\n\n',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '### 📊 规划统计\n\n',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '| 项目 | 详情 |\n|------|------|\n',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '| 🏛️ **景点数量** | 8个主要景点 |\n',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '| 💰 **预估费用** | ¥5,000 (不含机票) |\n',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '| ⏰ **行程时长** | 5天4晚 |\n',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '| 🏨 **酒店选择** | 3个不同档次选项 |\n\n',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '### 🎯 贴心提醒\n\n',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta:
      '> ⚠️ **重要提示**：\n> - 第3天有小雨，建议携带雨具\n> - 节假日景点可能拥堵，建议提前预订门票\n> - 北京地铁便利，推荐办理一卡通\n> - 品尝正宗北京烤鸭，推荐全聚德或便宜坊\n\n',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_CHUNK,
    messageId: null,
    delta: '✨ **祝您旅途愉快！**',
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  {
    type: AGUI_EVENT_TYPES.TEXT_MESSAGE_END,
    messageId: null,
    runId: null,
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
  // {
  //   type: AGUI_EVENT_TYPES.MESSAGES_SNAPSHOT,
  //   messages: [
  //     { id: generateMessageId(), role: 'user', content: '请为我规划一个北京5日游行程' },
  //     {
  //       id: generateMessageId(),
  //       role: 'assistant',
  //       content: '已为您完成北京5日游完整规划，包含天气预报、详细行程和酒店推荐。',
  //     },
  //   ],
  //   runId: null,
  //   agentId: 'travel-planner',
  //   timestamp: Date.now(),
  // },
  // {
  //   type: AGUI_EVENT_TYPES.CUSTOM,
  //   event: {
  //     type: 'travel_tip',
  //     tip: '🎫 建议提前在官网预订故宫门票，避免现场排队',
  //     category: 'booking_advice',
  //   },
  //   runId: null,
  //   agentId: 'travel-planner',
  //   timestamp: Date.now(),
  // },
  // {
  //   type: AGUI_EVENT_TYPES.RAW,
  //   event: {
  //     content: '北京5日游规划任务完成',
  //     metadata: {
  //       source: 'travel-planner',
  //       completion_time: new Date().toISOString(),
  //       total_events: 50,
  //       processing_duration: '45s',
  //     },
  //   },
  //   runId: null,
  //   agentId: 'travel-planner',
  //   timestamp: Date.now(),
  // },
  {
    type: AGUI_EVENT_TYPES.RUN_FINISHED,
    threadId: 'thread_001',
    runId: null,
    result: { totalAttractions: 8, estimatedCost: 5000, duration: '5天4晚' },
    agentId: 'travel-planner',
    timestamp: Date.now(),
  },
];
export { simpleAguiChunks, tourChunks, AGUI_EVENT_TYPES };
