name: pkg-pr-new

on: [push, pull_request]

jobs:
  build:
    if: ${{ github.repository == 'TDesignOteam/tdesign-web-components' && !startsWith(github.head_ref, 'release/') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm run "/^build:/"

      - run: pnpm dlx pkg-pr-new publish './packages/*' --compact --packageManager=pnpm,npm,yarn
