name: pkg-pr-new
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    if: ${{ github.repository == 'TDesignOteam/tdesign-web-components' && !startsWith(github.head_ref, 'release/') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - uses: actions/setup-node@v6
        with:
          node-version: 18

      - run: npm install

      - run: npm run build

      - run: npx pkg-pr-new publish
